### ISSUE TITLE
Test on my own dataset without GT.

### ISSUE THREAD

**Issue by zhouliu** [esw0116/DynaVSR#2]
Hi SuYoung,

Can you please comment on how to test DynaVSR on my own dataset without GT?  

Thanks:)

**Comment by esw0116** [comment]
Hello, 
I added the script to test DynaVSR model running on your test dataset.
Set the dataroot line of [EDVR_Demo.yml](https://github.com/esw0116/DynaVSR/blob/master/codes/options/test/EDVR/EDVR_Demo.yml#L37) to your folder containing images and run the test script.
It is also explained in the updated readme file.
Thank you.
