### ISSUE TITLE
Dataset Preparation

### ISSUE THREAD

**Issue by heiheihei-ops** [esw0116/DynaVSR#3]
I have noticed that the file 'make_downscaled_images.py' doesn't include the name 'vimeo', can I use this file to prepare dataset from vimeo-90k to train? looking for your reply, thank you!
https://github.com/esw0116/DynaVSR/blob/39e7abd3d21da3574238333561b8ed756111e9d4/codes/make_downscaled_images.py#L39

**Comment by esw0116** [comment]
Hello, I have just updated the script for downscaling Vimeo90K dataset.
It makes sequences of downscaled Vimeo90K test images.
Note that preset mode is not implemented when downscaling Vimeo90K.
Sorry for the late reply.
